parameters:
    env(PACKAGES_MIRROR): 'https://mirror.leaseweb.net/archlinux/'
    app.packages.mirror: '%env(PACKAGES_MIRROR)%'
    app.packages.cgit: 'https://projects.archlinux.de/svntogit/'
    app.packages.repositories:
        core: ['x86_64']
        extra: ['x86_64']
        testing: ['x86_64']
        community: ['x86_64']
        community-testing: ['x86_64']
        multilib: ['x86_64']
        multilib-testing: ['x86_64']
    app.packages.default_architecture: 'x86_64'
    app.mirrors.status: 'https://www.archlinux.org/mirrors/status/json/'
    env(DEFAULT_MIRROR): '%app.packages.mirror%'
    app.mirrors.default: '%env(DEFAULT_MIRROR)%'
    app.mirrors.country: 'DE'
    app.news.feed: 'https://bbs.archlinux.de/extern.php?action=feed&fid=257&type=atom&order=posted&show=15'
    app.releng.releases: 'https://www.archlinux.org/releng/releases/json/'
