exercise_html_purifier:
    default_cache_serializer_path: '%kernel.project_dir%/var/htmlpurifier/cache/%kernel.environment%'

    html_profiles:
        default:
            config:
                # the charset used by the original contents
                Core.Encoding: 'UTF-8'
                # full configuration reference: http://htmlpurifier.org/live/configdoc/plain.html

# Read the https://github.com/Exercise/HTMLPurifierBundle/blob/master/README.md file
# to know how to whitelist elements

#            # whitelist attributes by tag
#            attributes: []

#            # whitelist elements by name
#            elements: []

#            # list of elements that cannot have attributes
#            blank_elements: []
        release:
            config:
                HTML.Allowed: 'a[href],p,code,pre,ul,ol,li,br,strong,em'
                HTML.Nofollow: true
