version: "3.4"

services:
  cypress:
    image: cypress/included:5.3.0
    depends_on:
      - nginx
    environment:
      - CYPRESS_baseUrl=http://nginx
      - CYPRESS_numTestsKeptInMemory=100
      - DISPLAY
    entrypoint: cypress
    working_dir: /app
    volumes:
      - ../app:/app
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    ipc: host
    tmpfs:
      - /tmp
