version: "3.4"

services:
  api:
    build: php
    working_dir: /app/api
    environment:
      - HOME=/tmp
    user: "${UID}:${GID}"
    volumes:
      - ../api:/app/api
    tmpfs:
      - /tmp
    depends_on:
      - mariadb
      - elasticsearch
#      - elasticsearch-test

  app:
    image: node:alpine
    working_dir: /app/app
    environment:
      - HOME=/tmp
    command: yarn serve
    user: "${UID}:${GID}"
    volumes:
      - ../app:/app/app
    tmpfs:
      - /tmp

  nginx:
    build: nginx
    ports:
      - "8080:80"
    volumes:
      - ../:/app:ro
    tmpfs:
      - /tmp
    depends_on:
      - api
      - app

  mariadb:
    image: mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    tmpfs:
      - /tmp

#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    environment:
#      - PMA_HOST=mariadb
#      - PMA_USER=root
#      - PMA_PASSWORD=
#    ports:
#      - "8090:80"
#    tmpfs:
#      - /tmp
#    depends_on:
#      - mariadb

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    tmpfs:
      - /tmp

#  elasticsearch-test:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
#    environment:
#      - "discovery.type=single-node"
#      - "ES_JAVA_OPTS=-Xms4g -Xmx4g"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
#    tmpfs:
#      - /tmp
#
#  kibana:
#    image: docker.elastic.co/kibana/kibana:7.9.1
#    ports:
#      - "5601:5601"
#    depends_on:
#      - elasticsearch
#      - elasticsearch-test
#    tmpfs:
#      - /tmp

  wait:
    image: dokku/wait
